### ISSUE TITLE
Temporarily disabling pan

### ISSUE THREAD

**Issue by ttseng** [mjfisheruk/jquery.pan#1]
Thanks for creating this - very useful!

Is there a way to remove pan from an element temporarily?

**Comment by xpacmanx** [comment]
i found solution
#3

**Comment by mjfisheruk** [comment]
@ttseng: Thank you for your kind words, and I'm sorry for not getting back to you. I've not been properly engaged with github for a long time (as you can tell, five years later...!)

@xpacmanx: Thanks for stepping in. Your solution is a really clean way of doing it. I'm going to get PR #3 merged into a temporary branch, add the documentation for it to the README and get that merged into master.

**Comment by mjfisheruk** [comment]
And that's merged in as #4 with an updated README too. Many thanks, @ttseng and @xpacmanx
